### ISSUE TITLE
There is a way to use this package in forms view too when insert/update data ?

### ISSUE THREAD

**Issue by wemersonrv** [dcasia/resource-navigation-tab#1]
Hello, there is a way to use this package in forms view too when insert/update data ?

**Comment by milewski** [comment]
it's not possible because Nova doesnt support having cards on form views, basically what this package does is creating a card that seats above the table and toggles each instance of the navigation-tab-field on/off based on the active tab

**Comment by wemersonrv** [comment]
Ok understand...
