### ISSUE TITLE
Where to get a card from an example?

### ISSUE THREAD

**Issue by 4n70w4** [dcasia/resource-navigation-tab#10]
I really liked the card. Where can I get it?

![image](https://user-images.githubusercontent.com/38257723/76143017-5b2f5680-6084-11ea-8849-ae8da29fbcc1.png)

**Comment by milewski** [comment]
Hi, this package was internally created for our use case, it wouldn't make sense to publishing it to Github because all the functionality on it is 100% tied to our use case...

**Comment by 4n70w4** [comment]
@milewski Maybe there is a tutorial on how to do something similar?

**Comment by Milkhan** [comment]
+1 Yes, please!
