### ISSUE TITLE
If model use Actionable then every tab contains ActionEvent block

### ISSUE THREAD

**Issue by 4n70w4** [dcasia/resource-navigation-tab#14]
It would be very useful to show it in only one of the tabs.

https://nova.laravel.com/docs/2.0/actions/defining-actions.html#action-log

**Comment by milewski** [comment]
But isn't the action recorded once you actually execute an action? I don't understand how this plugin could avoid the action of being recorded

**Comment by 4n70w4** [comment]
I just don't want to see this block in every tab. Have an idea how to display in only one tab?

This displayed on every tab.
![image](https://user-images.githubusercontent.com/38257723/76407438-6512cb80-639c-11ea-95cb-545c5b795bb8.png)

**Comment by milewski** [comment]
Ahhh got it.. I thought you were referring to the actual content of this actions table, Yeah I think it's possible to remove it, I don't have time to look into it right now, but I will checkout asap

**Comment by milewski** [comment]
You can have a HasMany/BelongsToMany field within the `ResourceNavigationTab::make(['fields' => [HERE]])` this will avoid the relationship from being visible while the tab where it is within is not selected
