### ISSUE TITLE
Get ParseError syntax error, unexpected ')'  in HasResourceNavigationTabTrait.php:158

### ISSUE THREAD

**Issue by tititorn** [dcasia/resource-navigation-tab#18]
I try out Resource Navigation Tab with my nova resource

use DigitalCreative\ResourceNavigationTab\HasResourceNavigationTabTrait;
use DigitalCreative\ResourceNavigationTab\ResourceNavigationTab;

class Customer extends Resource
{
    use HasResourceNavigationTabTrait;

I got this error 
ParseError syntax error, unexpected ')'

vendor/digital-creative/resource-navigation-tab/src/HasResourceNavigationTabTrait.php:158

I'm using Laravel 7.6.1 and Nova 3.4.0 on PHP 7.2.24

Any suggestion?

**Comment by tititorn** [comment]
Please remove "," on line 157 in HasResourceNavigationTabTrait.php 
from 
   })->flatten(),
To
  })->flatten()

**Comment by milewski** [comment]
what PHP version are you using? can you submit a PR removing that comma

**Comment by tititorn** [comment]
PHP 7.2.24

**Comment by milewski** [comment]
This has been fixed already
