### ISSUE TITLE
How To work with : fieldsForIndex, fieldsForDetail, fieldsForCreate, fieldsForUpdate

### ISSUE THREAD

**Issue by issour** [dcasia/resource-navigation-tab#20]
Many thx !!!

**Comment by milewski** [comment]
I think i have not considered this case, can you show some code of what you are trying to do?

**Comment by issour** [comment]
Hello @milewski !

In fact, every resource have now with the new version of Nova : 

1- public function fields(Request $request)
2- public function fieldsForIndex(NovaRequest $request)
3- public function fieldsForDetail(Request $request)
4- public function fieldsForCreate(NovaRequest $request)
5- public function fieldsForUpdate(NovaRequest $request)

Your Awesome package "resource-navigation-tab", should take over only in request detail mode;
in fact checking if request is in detail mode : isResourceDetailRequest().

Of course with resolving fields by checking if function fieldsForIndex(NovaRequest $request)  exist, if not resolving fields from public function fields(Request $request) : 
According to Nova documentation -> 
The fieldsForIndex, fieldsForDetail, fieldsForCreate, and fieldsForUpdate methods always take precedence over the fields method.

Thx for your :)

**Comment by milewski** [comment]
I see so the issue is that you are not using the fields() method at all?

**Comment by issour** [comment]
Hi @milewski 
exactly, when you call fieldsForIndex it will take over fields.

**Comment by issour** [comment]
Hi @milewski 

can you use the same solution for 'conditional-container' : 
```
$method = $this->fieldsMethod($request);
$allFields = $this->{$method}($request);
```
Many Thx

**Comment by milewski** [comment]
@issour can you make these changes and test on your project? I don't have a project here that I can quickly set this up to see if it works correctly atm (you can modify the files directly from within the vendor folder to test this out)

**Comment by milewski** [comment]
Done.. added support on version `v1.0.3`
