### ISSUE TITLE
Problem in lenses: show all tab fields on index table

### ISSUE THREAD

**Issue by 4n70w4** [dcasia/resource-navigation-tab#21]
Hi! Example lense returns all fields from resuorce:

```php

class ResourceLens extends Lens {

    use HasResourceNavigationTabTrait;


    public function fields(Request $request) {
        $res = new Resource(new \Models\Model() );

        // return all the same fields
        return $res->fields($request);
    }

}
```

Resource fileds grouped in `ResourceNavigationTab`. But in Lens index table displayed all fields with fields from `ResourceNavigationTab`.

**Comment by 4n70w4** [comment]
Workaround:

```php
        return collect($res->fields($request))->filter(function ($value, $key) {
            return false === $value instanceof ResourceNavigationTab;
        })->toArray();
```

**Comment by milewski** [comment]
Well, this package was only meant to be used on the details view, not on index. so I will discard this as a bug on index view you can use this other package: https://github.com/dcasia/resource-navigation-link which only works on the index and looks exactly the same as this one
