### ISSUE TITLE
Feature: use in action fields

### ISSUE THREAD

**Issue by 4n70w4** [dcasia/resource-navigation-tab#22]
Hi! It will be very convenient to be able to split fields into action groups like resource form:

![image](https://user-images.githubusercontent.com/38257723/81181156-b1514500-8fb4-11ea-8120-a103156061bc.png)

https://nova.laravel.com/docs/3.0/actions/defining-actions.html#action-fields

Currently I get expection if add `ResourceNavigationTab` to Action fields:

```
Call to undefined method DigitalCreative\ResourceNavigationTab\ResourceNavigationTab::resolve()
```

**Comment by milewski** [comment]
I don't understand how are you planning to use this package within an action field? this package only works on details.. action field shows within a modal.. so I'm not sure what you mean
