### ISSUE TITLE
Doesn't work on Nova v2.11.1

### ISSUE THREAD

**Issue by setysoft** [dcasia/resource-navigation-tab#25]
Just shows nothing like without ResourceNavigationTab wrapper. 
Any suggestion?

return [
                ResourceNavigationTab::make([
                    'label' => 'Information',
                    'fields' => [
                        ID::make()->sortable(),
                        ]
                ]),
                ResourceNavigationTab::make([
                'label' => 'Information 23354',
                'fields' => [
                    ID::make()->sortable(),
                ]
            ]),
        ];

Shows 2 columns Id, no tabs

**Comment by milewski** [comment]
Did you forgot to include the trait? 
`use HasResourceNavigationTabTrait; `

**Comment by ncatanchin** [comment]
This is a problem for me as well.

Have seem in another one of your projects that Nova 3 is now required. I'm getting the `fieldsMethod()` error.

Probably something to solve via `composer.json` to avoid upgrade for those still using Nova 2

**Comment by milewski** [comment]
Sorry about that I will start adding the constraints on the composer.json files

**Comment by ncatanchin** [comment]
Thanks, very grateful for the awesome packages that you make available!
