### ISSUE TITLE
detailFieldsWithinPanels problem

### ISSUE THREAD

**Issue by crzzano** [dcasia/resource-navigation-tab#29]
Looks like this package isn't compatible with latest versions of Nova

ErrorException
Declaration of DigitalCreative\ResourceNavigationTab\HasResourceNavigationTabTrait::detailFieldsWithinPanels(Laravel\Nova\Http\Requests\NovaRequest $request, Laravel\Nova\Resource $resource) should be compatible with Laravel\Nova\Resource::detailFieldsWithinPanels(Laravel\Nova\Http\Requests\NovaRequest $request)

**Comment by milewski** [comment]
It has been fixed already on the latest version: https://github.com/dcasia/resource-navigation-tab/releases/tag/v1.1.0
