### ISSUE TITLE
Panels inside tabs?

### ISSUE THREAD

**Issue by luke0x90** [dcasia/resource-navigation-tab#3]
Is there a way to get panels inside tabs? I have too many tabs at the moment and to reduce the amount id like to split each tab into subsections.

There is also a minimum width bug if you have too many tabs where it overflows onto the side nav bar 

cheers

**Comment by milewski** [comment]
I think currently only the cards obey the tabs, but yeah wouldn't be hard to add the panels to follow the same logic too, Im a bit busy currently wouldn't be able to improve on this so soon, but if you know how to do it PRs are welcome!

**Comment by luke0x90** [comment]
Hi, 

Ive settled with using Heading::make field as it allows embedded html and does a good enough job. 

Cheers x
