### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by pooryasadidi6868** [dcasia/resource-navigation-tab#30]
Declaration of DigitalCreative\ResourceNavigationTab\HasResourceNavigationTabTrait::detailFieldsWithinPanels(Laravel\Nova\Http\Requests\NovaRequest $request, Laravel\Nova\Resource $resource) should be compatible with Laravel\Nova\Resource::detailFieldsWithinPanels(Laravel\Nova\Http\Requests\NovaRequest $request)

**Comment by milewski** [comment]
Are you using the latest version of nova and this package?

**Comment by pooryasadidi6868** [comment]
fixed after update nova to latest version
