### ISSUE TITLE
Trait collision

### ISSUE THREAD

**Issue by eboye** [dcasia/resource-navigation-tab#31]
I've tried to implement this package, but have this error when I try to add it to my resource where I have [JsonWrapper](https://github.com/dcasia/nova-json-wrapper) pacakge.

```
Trait method 'availableFields' will not be applied, because it collides with 'HasJsonWrapper'
Trait method 'availablePanelsForDetail' will not be applied, because it collides with 'HasJsonWrapper'
```

What can I do to make it work? Any ideas? Or is it not possible at all?

Thanks

**Comment by nchicas** [comment]
Hey @eboye, I had the same problem before. In my case I had a trait that was used in forms and tabs in the detail, so I checked if I'm creating or updating a resource to use availableFields from my other Trait.

`use HasResourceNavigationTabTrait, HasDependencies {
			HasResourceNavigationTabTrait::availableFields as tabFields;
			HasDependencies::availableFields as dependencyFields;
		}

		// Dependency only should be presented in forms and tabs in views
		public function availableFields(NovaRequest $request)
		{
				if($request->isCreateOrAttachRequest() ||
				   $request->isUpdateOrUpdateAttachedRequest())
				{
						return $this->dependencyFields($request);
				}
				else 
				{
						return $this->tabFields($request);
				}
		}`

**Comment by milewski** [comment]
On the latest version now supporting nova 4 this is no longer an issue I avoided overriding those methods and collision will be very unlikely
