### ISSUE TITLE
Hide/Show Tab

### ISSUE THREAD

**Issue by ErenPhayte** [dcasia/resource-navigation-tab#35]
Is there a way to hide/show tab based on rules i.e. permissions or any other rules based on the values of a Resource?

**Comment by milewski** [comment]
You can always do something like this:

```php
class ExampleNovaResource extends Resource {

    public function fields(Request $request)
    {
        if($request->user()->can(.....)) {
            return [
                ResourceNavigationTab::make([ 'label' => 'Only for admin' ]),
            ];
        }

        return [
            ResourceNavigationTab::make([ 'label' => 'Public' ]),
        ];
    }

}
```

**Comment by ErenPhayte** [comment]
Thanks. But what if its needs to show or hide by Resource values I.e. I
have Pages and you can clone them. Only for pages that have been cloned I
want a tab that shows which pages were the clone (children parent
relationship)

**Comment by milewski** [comment]
I think its still the same concept, you dynamically build the array of fields based on your condition.. if you need 3 tabs.. return 3 instances of `ResourceNavigationTab` .. so on..

**Comment by milewski** [comment]
The latest version respects the authorization of the fields, so besides the solution mentioned above the tab will also hide if the user inst allowed to see any of the fields contained within.
