### ISSUE TITLE
How can i show other relation ship data which is not directly linked with table?

### ISSUE THREAD

**Issue by jigarhalani** [dcasia/resource-navigation-tab#4]
For example, I have a subscription table, user table and billing table.

Subscription has direct relationship with user and user have relationship with billing so in subscription resource how can i show all billing table data?

**Comment by milewski** [comment]
Place your relationships outside of `ResourceNavigationTab` this way all your relationship will be available on all the tabs:

```php
    public function fields(Request $request)
    {
        return [
            ResourceNavigationTab::make('Information', [
                .....
            ])
            BelongsToMany::make('...'),
            HasMany::make('...'),
        ];
    }
```

**Comment by milewski** [comment]
You cant show data that is not linked with this package, what this package does behind the scene is just hide/show your fields depending on the current active tab, so you can only do what is currently possible to do natively in nova, 

The only difference of using this package and not using it is that **without this package** everything shows on the same page (if you have 10 relationships, all 10 relationships are shown on the same page) but with this package, you can group this 10 relationship into different tabs.
