### ISSUE TITLE
Broken layout

### ISSUE THREAD

**Issue by 4n70w4** [dcasia/resource-navigation-tab#55]
Hi!

Nova v3.30.0
digital-creative/resource-navigation-tab (v1.1.1)

![image](https://user-images.githubusercontent.com/38257723/161383693-fc563df9-c7d7-4231-84c7-c4d021417729.png)

**Comment by priithansen** [comment]
@4n70w4 do You by any chance have also installed "optimistdigital/nova-tailwind". I think the layout conflict might come from that causing .w-full class to go missing from css.

**Comment by milewski** [comment]
A new version was released with Nova 4 support, this might not be an issue anymore
