### ISSUE TITLE
Nova 4 support

### ISSUE THREAD

**Issue by bartdenhoed** [dcasia/resource-navigation-tab#56]
We would like to use this package in Nova 4.

**Comment by yburlakov** [comment]
@milewski, could you please clarify, when do you plan to implement support for Nova 4?

**Comment by milewski** [comment]
Hi @yburlakov currently I don't have enough bandwidth to go through and upgrade all the packages to nova 4... There are way too many packages that need to be essentially remade...

**Comment by bartdenhoed** [comment]
We use eminiarts/nova-tabs now, the have updated to support Nova 4. Maybe others are happy to use it as well.

**Comment by milewski** [comment]
Now it works in Nova 4 [v2.0.0](https://github.com/dcasia/resource-navigation-tab/releases/tag/v2.0.0)
