### ISSUE TITLE
Toolbar on all tabs

### ISSUE THREAD

**Issue by MorganeMeganck** [dcasia/resource-navigation-tab#6]
Is it possible to have the toolbar for delete and update on all the tabs? Or on top of the tabs?
It's a little bit confusing to have to go on the first tab to have access to the update button

Thx for this great package

**Comment by milewski** [comment]
For that you need at least 1 field of your main resource on all the tabs.. for example:

```php
public function fields(Request $request)
{
    return [
        ResourceNavigationTab::make('Tab A', [
            ID::make()->sortable(),
        ]),
        ResourceNavigationTab::make('Tab B', [
            ID::make()->sortable(),            
        ]),
        ResourceNavigationTab::make('Tab C', [
            ID::make()->sortable(),
        ]),
    ];
}
```
