### ISSUE TITLE
conflict when using you packages MegaFilter and ResourceNavigationTab in the same resource

### ISSUE THREAD

**Issue by khitas** [dcasia/resource-navigation-tab#60]
When using your packages "Resource Navigation Tab" and "Nova Mega Filter" in the same resource i get the following error:

Trait method DigitalCreative\ResourceNavigationTab\HasResourceNavigationTabTrait::availableFields has not been applied as App\Nova\Garage::availableFields, because of collision with DigitalCreative\MegaFilter\HasMegaFilterTrait::availableFields

Can you please fix that error? 
<img width="1390" alt="Screenshot 2022-10-13 at 11 19 16 PM" src="https://user-images.githubusercontent.com/1069228/195702022-f26b6fd6-e1d2-4aa0-af7d-50955d419e97.png">

**Comment by milewski** [comment]
This is no longer an issue on the latest version, I have rewritten the package and avoided using those conflicting methods.
