### ISSUE TITLE
Nova.visit(window.location.pathname) returns 404 not found status

### ISSUE THREAD

**Issue by goszowski** [dcasia/resource-navigation-tab#70]
Nova.visit(window.location.pathname) make request to /**nova/nova**/resources... and returns 404.

**Comment by milewski** [comment]
Can you give me a sample code so I can easily copy/paste it to reproduce the issue locally?

**Comment by goszowski** [comment]
Just install a fresh laravel project, install nova and your package. Make two tabs and click on one. You'll see 404 not found error. 

This happens through this piece of code: https://github.com/dcasia/resource-navigation-tab/blob/main/resources/js/components/ResourceNavigationCard.vue#L82

It seems that Nova.visit already takes the "nova" prefix when generating destination URL.

<img width="1201" alt="SCR-20231001-n11" src="https://github.com/dcasia/resource-navigation-tab/assets/10208931/40382769-8490-47cd-a722-3eb6d2f15279">
<img width="1195" alt="SCR-20231001-n1a" src="https://github.com/dcasia/resource-navigation-tab/assets/10208931/067e2a72-afc0-48b4-aab0-a9bb8941b736">
<img width="473" alt="SCR-20231001-n1o" src="https://github.com/dcasia/resource-navigation-tab/assets/10208931/10b6887c-f0f4-4aa3-8e3f-52a26edc1ead">

**Comment by milewski** [comment]
Oh, I see. I always run this with the `nova.docker.localhost` domain, that's why I didn't catch this. Okay, I will fix it soon.

**Comment by milewski** [comment]
Fixed on [v2.1.1](https://github.com/dcasia/resource-navigation-tab/releases/tag/v2.1.1)
