### ISSUE TITLE
Problem on Octane (roadrunner)

### ISSUE THREAD

**Issue by goszowski** [dcasia/resource-navigation-tab#72]
Default (first) tab is empty. 

Steps to reproduce:
1. Install fresh Laravel application
2. Install Laravel Nova
3. Install Laravel Octane (Roadrunner)
4. Run php artisan octane:start
5. Go to resource
6. Refresh page a few times

Demonstration video: https://www.youtube.com/watch?v=GcA4ixZAlwc

**Comment by milewski** [comment]
Fixed [v2.1.2](https://github.com/dcasia/resource-navigation-tab/releases/tag/v2.1.2)
