### ISSUE TITLE
Use as Main Tab with Subtabs

### ISSUE THREAD

**Issue by khitas** [dcasia/resource-navigation-tab#76]
I used to use this package for nova 3 compined with eminiarts/nova-tabs or dkulyk/nova-tabs etc to create Tabs with SubTabs. I used this package for main Tab and the other package for SubTabs but for nova 4 version this package is not compatible with that functionality. Every package i try to use for subtabs not displayed. Attached you can see the described example for nova3.

Can you please give a solution for this problem ?

![Untitled 2](https://github.com/dcasia/resource-navigation-tab/assets/1069228/84ffb336-955d-4e0c-9dbe-59a7d839e028)

**Comment by milewski** [comment]
Can you be more specific? what is not working? What is the error you are getting? is the subtab that is not working or this package that is not working? do you have an error message? is there js errors on the console?
