### ISSUE TITLE
Reloading page

### ISSUE THREAD

**Issue by philipbaginski** [dcasia/resource-navigation-tab#80]
#Laravel 10
#Last version of Nova

The reality: Every time tab is changed, page is reloaded.

The question: Is it possible to do something to avoid reloading page, when we click on another tab?

**Comment by milewski** [comment]
It is not possible without overriding the native nova components, the nova3 version of this package did not reload the entire page and that caused many issues, on this re-write i choose not to do the same strategy and now this package is way more stable

**Comment by philipbaginski** [comment]
I see it. Thank you.
